Add MPU6050 library and sample code
SmingHub/Sming pull request #2655
Opened 2023-07-28 10:26 UTC by xeonqq

2023-07-28 12:43 UTC, mikee47 reviewed
A few thoughts

2023-07-28 14:16 UTC, xeonqq commented
After a closer examination, I realized the quaternion related code is not used in this part of the library (see [here](https://github.com/SmingHub/Sming/pull/2655/files#diff-ecc89b792b3b1fdbd6efe09c73dc777fc73ea29968ae8366a2c1ca37d1f3dc6fR6)). So I simply deleted it to keep the library lean.

The other comments of yours I have addressed. Thank you for the feedback. Please have a look again~

2023-07-29 10:12 UTC, slaff commented
@mikee47 The build with IDF v5.0 is failing. I was able to reproduce the issue on my machine and it seems to not be related to this PR. Can you check if we have to downgrade/upgrade the pyparse version?
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen.py", line 183, in <module>
    main()
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen.py", line 159, in main
    mapping_rules = generation_model.generate(sections_infos)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 514, in generate
    root_node.insert(entity, sections, target, flags, entities)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 233, in child_placement
    child.insert(entity, sections, target, flags, sections_db)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 233, in child_placement
    child.insert(entity, sections, target, flags, sections_db)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 241, in insert
    self.child_placement(entity, sections, target, flags, sections_db)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/generation.py", line 296, in child_placement
    found_sections = sections_db.get_sections(self.parent.name, self.name)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/entity.py", line 197, in get_sections
    obj = self._match_obj(archive, obj)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/entity.py", line 183, in _match_obj
    objs = self.get_objects(archive)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/entity.py", line 176, in get_objects
    self._process_archive(archive)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/entity.py", line 164, in _process_archive
    parsed = self._get_infos_from_file(stored)
  File "/opt/esp-idf-5.0/tools/ldgen/ldgen/entity.py", line 154, in _get_infos_from_file
    raise ParseException('Unable to parse section info file ' + info.filename + '. ' + p.msg)
pyparsing.exceptions.ParseException: Unable to parse section info file /home/runner/work/Sming/Sming/Sming/out/Esp32/esp32/debug/build/esp32/sdk/esp-idf/esp_event/libesp_event.a. Expected end of text  (at char 0), (line:1, col:1)
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 2.
```

2023-07-29 11:52 UTC, mikee47 reviewed
This is an example of code which got written with a 'C' viewpoint rather than C++. More robust, easier to manage and safer to use references instead of pointers, structures instead of long parameter lists, etc. Hopefully this all makes sense?

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.cpp
> + */
If you want to make use of  comments to appear in the documention they should be in the header file.

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +
Remove. That redefinition of `pgm_read_byte` will cause issues for esp8266.

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +
`#pragma once` preferred

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +	uint8_t buffer[14] = {0};
Remove. Methods should use local variables.

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/README.md
> +Based on code from [jrowberg/i2cdevlib](https://github.com/jrowberg/i2cdevlib/tree/master/ESP32_ESP-IDF/components/MPU6050). Most of the code is the same, except:
Maybe date and which commit this is based on.

Can also add doxygen documentation, but requires this file to be renamed to `README.rst` and heading/url adjusted accordingly.

```
API Documentation
-----------------

.. doxygenclass:: MPU6050
   :members:

```

2023-07-29 11:52 UTC, mikee47 commented on samples/Accel_Gyro_MPU6050/app/application.cpp
> +
```
void mainLoop()
{
	MPU6050::Motion6 motion;
	mpu.getMotion6(motion);
        Serial << motion << endl;
}
```

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.cpp
> +	return buffer[0];
Use stack for buffer.

```
uint8_t b;
I2Cdev::readBit(devAddr, MPU6050_RA_YG_OFFS_TC, MPU6050_TC_PWR_MODE_BIT, &b);
return b;
```

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.cpp
> +	return buffer[0];
Use stack for buffer.

```
uint8_t b;
I2Cdev::readByte(devAddr, MPU6050_RA_SMPLRT_DIV, &b);
return b;
```

or use private helper:

```
return readByte(MPU6050_RA_SMPLRT_DIV);
```

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.cpp
> +	return buffer[0];
`return readBits(MPU6050_RA_CONFIG, MPU6050_CFG_EXT_SYNC_SET_BIT, MPU6050_CFG_EXT_SYNC_SET_LENGTH);`

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.cpp
> +	return (buffer[0] >> 3) | ((buffer[1] >> 2) & 0x03);
Using helpers:

```
uint8_t y = readByte(MPU6050_RA_SELF_TEST_Y);
uint8_t a = readByte(MPU6050_RA_SELF_TEST_A);
return (y >> 3) | ((a >> 2) & 0x03);
```

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/component.mk
> +COMPONENT_DEPENDS := I2Cdev
To make doxygen comments available (from .h files) add `COMPONENT_DOXYGEN_INPUT := .`

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +// note: DMP code memory blocks defined at end of header file
Remove (or edit to make sense)

2023-07-29 11:52 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +#endif /* _MPU6050_H_ */
Remove (#pragma once)

2023-08-01 17:20 UTC, xeonqq commented
Thanks for the review, I agree the old code which I copy/paste is not to the standard of Sming. I will do the refactoring when I find time.  Currently I want to first prototype the balance robot I am working on:)

2023-09-12 09:37 UTC, slaff commented
@xeonqq are you ready with all changes to this PR?

2023-09-13 11:45 UTC, xeonqq commented
> @xeonqq are you ready with all changes to this PR?

No, not yet, there are still many comments I didn't address yet. Quite some workload. I will remove the wip tag in the PR title once I am ready for another review.

2023-11-04 15:39 UTC, xeonqq commented
@mikee47 ready for review again. Sorry for the delayed PR.
I in the end deleted Calibration and Memory Block related code for simplicity and code quality reason, anyway that is not frequently used functionality.
I fail one of the CI checks, it's about some clock cycles I am not sure if it's related to my change.

2023-11-07 11:17 UTC, mikee47 commented
> I fail one of the CI checks, it's about some clock cycles I am not sure if it's related to my change.

Does that sometimes, host emulator isn't perfect :-( Re-running the test

2023-11-07 11:27 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +
Most (if not all) of these macros are for internal use by the class. Suggest moving them into a separate header file so they don't clutter the global namespace.

2023-11-07 11:27 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +	MPU6050(uint8_t address) : devAddr{address}
`uint8_t` -> `SlaveId`

2023-11-07 11:28 UTC, mikee47 commented on Sming/Libraries/MPU6050/MPU6050.h
> +	struct Motion3 {
using SlaveId = uint8_t;

2023-11-07 11:44 UTC, mikee47 commented on Sming/Libraries/MPU6050/README.rst
> +
Move this to the bottom of the file for consistency - it gets expanded into a lot of information.

2023-11-07 11:54 UTC, mikee47 commented on Sming/Libraries/MPU6050/README.rst
> +-   Deleted Calibration and Memory Block related code for code quality reason
Have a look at other libraries/Components for general layout. Heading must be double-underlined (level 1) and give a good name for the library. For example:

```
MPU6050 Gyro / Accelerometer
============================
```

Follow this with the description. Note that `.rst` files (restructured text) syntax differs from markdown so remember to fix links, e.g.

```
`jrowberg/i2cdevlib<https://github.com/jrowberg/i2cdevlib/tree/master/ESP32_ESP-IDF/components/MPU6050>`
```

And put the API section last.

2023-11-07 14:01 UTC, mikee47 requested changes
You've inadvertently reverted the `FlashString` and `IFS` libraries! Other than that, and the documentation change, looks great! I assume it's all working and tested on actual hardware?

2023-11-07 14:36 UTC, xeonqq commented
> You've inadvertently reverted the `FlashString` and `IFS` libraries! Other than that, and the documentation change, looks great! I assume it's all working and tested on actual hardware?

I just realized that too, and reverted the unintended change of the submodules. 

I tested on esp8266 and mpu6050, but only the functions used in the sample program. So I can't say for sure it is bullet proof.
And tested assertion is working as expected.

2023-11-07 20:30 UTC, mikee47 commented on Sming/Libraries/MPU6050/README.rst
> +
Almost... remove `:members:` and line starting '#'. Also the URL requires __ at the end!

```
Based on code from `jrowberg/i2cdevlib <https://github.com/jrowberg/i2cdevlib/tree/master/ESP32_ESP-IDF/components/MPU6050>`__ @ 605a740. Most of the code is the same, except:
```

2023-11-07 20:40 UTC, mikee47 commented on Sming/Libraries/MPU6050/README.rst
> +-   Deleted Calibration and Memory Block related code for code quality reason
Yeah, takes a bit of getting used to but has advantages to markdown! See https://sming.readthedocs.io/en/latest/information/develop/documentation.html

2023-11-08 09:37 UTC, slaff requested changes
Fix small typos.

2023-11-08 09:37 UTC, slaff commented on Sming/Libraries/MPU6050/MPU6050.cpp
> +// NOTE: THIS IS ONLY A PARIAL RELEASE. THIS DEVICE CLASS IS CURRENTLY
Fix typo, replace  `PARIAL` with `PARTIAL`.

2023-11-08 09:37 UTC, slaff commented on Sming/Libraries/MPU6050/MPU6050.h
> +// NOTE: THIS IS ONLY A PARIAL RELEASE. THIS DEVICE CLASS IS CURRENTLY
Fix typo, replace  `PARIAL` with `PARTIAL`.

2023-11-08 09:37 UTC, slaff commented on Sming/Libraries/MPU6050/MPU6050.h
> +	//data follow big endien convention
Fix typo, replace `endien` with `endian`.

2023-11-08 09:51 UTC, mikee47 approved these changes

2023-11-08 14:44 UTC, xeonqq commented on Sming/Libraries/MPU6050/MPU6050.h
> +	//data follow big endien convention
done

2023-11-08 15:15 UTC, slaff approved these changes

2023-11-09 09:24 UTC, merged