[WIP] Add Host MacOS support
SmingHub/Sming pull request #2804
Opened 2024-06-16 16:38 UTC by mikee47

This PR adds support for the Host Emulator to MacOS.

**64-bit only**

Standard compiler is 'Apple Clang', supports only 64-bit builds: no 32-bit compatibility.
GCC can be installed via `brew install gcc` and compiles as usual with the `-m32` flag.
The GNU linker is absent from brew's `coreutils` package (see https://github.com/Homebrew/homebrew-core/issues/17794)
so the standard system linker must be used.
This only supports 64-bit targets.
Apple have removed 32-bit application support from their ecosystem.

Advantages
    No need for 32-bit compatibibility libraries in GNU/Linux.
    For MacOS build and run host emulator using standard Apple tools, no GCC required.
    General improvements in portability, less tolerant of incorrect type usage.

Disadvantages
    Types such as long, size_t now 64-bit
    Pointers are 64-bit so cannot be case to 32-bit intrinsics

**Symbol wraping**

MacOS linker doesn't support symbol wrapping which is used by `malloc_count` Component
to hook `malloc`, etc.

Don't currently have a solution for this so builds must use `ENABLE_MALLOC_COUNT=0`.

**CI builds**

For the time being this PR only includes MacOS builds.

Including MacOS build in regular CI might be excessive.
We might consider some CI refinements such as:

- Only run CI build on trigger by admin, instead of every single push
- Be specific about which combinations to run

This is supported for library testing using a 'CI Dispatch' workflow.
Could also use tags.
Other options?

**Notes**

MacOS identified in makefiles with `UNAME=Darwin`.
In code, use `#ifdef __APPLE__` when running on apple toolchains.
Also requires `#ifdef __aarch64__` for Apple Silicon.

I managed to get MacOS Ventura running in Qemu via https://github.com/kholia/OSX-KVM.
This runs in x86_64 mode, adequate for dev/testing.
The github actions runner `macos-latest` uses arm64, so introduces a few extra quirks.

**Tools**

Compiler
    Standard compiler is 'Apple Clang', supports only 64-bit builds: no 32-bit compatibility.
    Doesn't support `alias` attribute so use linker to do that instead.

Archiver
    Standard `ar` does not support 

Linker
    GNU Linker not available.
    MacOS linker has some issues.

GDB
    Can be installed with `brew` but requires some additional steps for security reasons as it
    can hook other processes.
    The standard `lldb` tool is fine but isn't currently integrated into framework.

sed
    GNU 'sed' tool has extensions which MacOS version does not support.
    Added `SED` build variable which should always point to GNU version `gsed`, but only for Darwin.

TODO:

* [ ] Make GNU/Linux Host build type selectable between 32/64-bit
* [ ] Add `lldb` support to framework
* [ ] Pull out fixes into separate PR, merge first

2024-06-18 08:43 UTC, slaff commented
> How to create virtual TAP for MacOS? Document.

Take a look here: 
https://groups.google.com/g/tunnelblick-discuss/c/v5wnQCRZ8HY/m/Q8nhFBx1BgAJ

2024-06-19 15:22 UTC, mikee47 commented
The networking works as follows. First, install tap extension:

```
sudo cp -r "$SMING_HOME/Arch/Host/Tools/macos/tap.kext" /Library/Extensions
sudo kextload /Library/Extensions/tap.kext
```

There's some security guff to manually deal with, then a reboot is required. (NB. this doesn't work in CI environment but gracefully fails.)

The Sming application must be run as sudo also. Changing permissions for `/dev/tap0` doesn't help, still get network write failures. I've tested this with the `HttpServer_ConfigNetwork` sample, running

```
sudo out/Host/debug/firmware/app
```

Then browsing to 192.168.13.10.

This kernel extension creates The `/dev/tap0` device. However, the actual `tap0` interface is created dynamically when the device is opened, as can be illustrated below. This post was most helpful https://stackoverflow.com/a/3125964.

```
sudo su
exec 4<>/dev/tap0
ifconfig
```

So two questions remain:

1. How to do this without requiring sudo? Slaff's post above suggests that the tunnelblick daemon does this sort of stuff, but that adds way more complexity than I'd like so haven't spend time on that.
2. How to configure routing so we can access internet?

2024-06-21 12:34 UTC, slaff requested changes

2024-06-21 12:34 UTC, slaff commented on docs/source/arch/host/index.rst
> +For Linux, uou can use ``Sming/Arch/Host/Tools/setup-network-linux.sh``. Here is the manual approach::
`uou can use` -> `you can use`

2024-06-21 12:34 UTC, slaff commented on docs/source/getting-started/macos/index.rst
> +   export SMING_HOME=opt/Sming/Sming
`export SMING_HOME=opt/Sming/Sming`

Either change this command to `export SMING_HOME=/opt/Sming/Sming` or revert this line.

2024-06-21 12:34 UTC, slaff commented on docs/source/getting-started/macos/index.rst
>  Make sure to replace ``<your-favourite-development-folder>`` in the
If you change it to `/opt/Sming/Sming` this sentence can be removed.

2024-06-21 14:13 UTC, mikee47 commented
@slaff There's still a couple of APPVEYOR references in `Tools/ci/install.sh` and `Sming/Arch/Host/Tools/install.sh`. The latter can go but the first one relates to deployment, which is your area... separate PR?

2024-06-21 14:14 UTC, slaff commented
> The latter can go but the first one relates to deployment, which is your area... separate PR?

I will take care of this next week in a separate PR.

2024-06-24 07:42 UTC, merged